export const MoviesDataActionTypes = {
  GET_MOVIES: 'GET_MOVIES',
  GET_MOVIE_GENRES: 'GET_MOVIE_GENRES',
  ADD_MOVIE_REVIEW: 'ADD_MOVIE_REVIEW',
  TOGGLE_REVIEW_TEXT_HIDDEN: 'TOGGLE_REVIEW_TEXT_HIDDEN',
  SELECT_WATCHED: 'SELECT_WATCHED',
  LEAVE_REVIEW: 'LEAVE_REVIEW'
};
