export const ReviewActionTypes = {
  ADD_MOVIE_RATE: 'ADD_MOVIE_RATE',
  ADD_MOVIE_GENRE: 'ADD_MOVIE_GENRE',
  ADD_MOVIE_TITLE: 'ADD_MOVIE_TITLE',
  ADD_MOVIE_REVIEW_TEXT: 'ADD_MOVIE_REVIEW_TEXT',
  ADD_MOVIE_POSTER_LINK: 'ADD_MOVIE_POSTER_LINK',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  RESET_REDUCER_DATA: ' RESET_REDUCER_DATA',
};
